# Generated by Django 2.2.12 on 2020-07-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='订单编号')),
                ('order_area', models.CharField(max_length=100, verbose_name='所在地区')),
                ('order_addr', models.CharField(max_length=100, verbose_name='收货地址')),
                ('order_recv', models.CharField(max_length=50, verbose_name='收货人')),
                ('order_tele', models.CharField(max_length=11, verbose_name='联系电话')),
                ('order_fee', models.IntegerField(default=10, verbose_name='运费')),
                ('order_extra', models.CharField(max_length=200, verbose_name='订单备注')),
                ('order_status', models.IntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收款'), (4, '已完成')], default=1, verbose_name='订单状态')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(verbose_name='商品数量')),
                ('goods_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='所属商品')),
                ('goods_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.OrderInfo', verbose_name='商品所属订单')),
            ],
        ),
    ]
