# Generated by Django 2.2.12 on 2020-07-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserpProfile',
            new_name='UserProfile',
        ),
    ]
