# Generated by Django 2.2.12 on 2020-07-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cag_name', models.CharField(max_length=30, verbose_name='分类的名称')),
                ('cag_css', models.CharField(max_length=20, verbose_name='分类的样式')),
                ('cag_img', models.ImageField(upload_to='cag', verbose_name='分类的图片')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='商品价格')),
                ('goods_inventory', models.CharField(default=0, max_length=20, verbose_name='商品库存')),
                ('goods_desc', models.TextField(verbose_name='商品描述')),
                ('goods_img', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('goods_cag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品分类')),
            ],
        ),
    ]
