# Generated by Django 2.2.12 on 2020-07-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('gander', models.CharField(max_length=11, verbose_name='性别')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
                ('birthday_day', models.CharField(max_length=20, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'vip0'), (1, 'vip1'), (2, 'vip2'), (3, 'vip3'), (4, 'vip4'), (5, 'vip5'), (6, 'vip6'), (7, 'vip7'), (8, 'vip8'), (9, 'vip9'), (10, 'vip10')], default=0, verbose_name='会员等级')),
                ('integrals', models.CharField(default=0, max_length=50, verbose_name='总积分')),
                ('ava_int', models.CharField(default=10, max_length=50, verbose_name='可用积分')),
                ('discounts', models.CharField(default=10, max_length=50, verbose_name='优惠折扣')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='所在地区')),
                ('addr', models.CharField(max_length=100, verbose_name='收货地址')),
                ('name', models.CharField(max_length=30, verbose_name='收货人')),
                ('telephone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户ID')),
            ],
        ),
    ]
